import type { Category } from './types';

export const categories: Category[] = [
  {
    id: 'segunda-via',
    title: '2ª Via',
    description: 'Contas de água, energia, internet e título de eleitor.',
    color: '#1565C0',
    lightColor: '#E3F2FD',
    icon: 'receipt',
    services: [
      {
        id: 'jupiter',
        name: 'Júpiter (Internet)',
        description: '2ª via do boleto de internet',
        url: 'https://www.jupiterinternet.com.br',
      },
      {
        id: 'saae',
        name: 'SAAE (Água)',
        description: '2ª via da conta de água',
        url: 'https://saaeacailandia.com.br',
      },
      {
        id: 'equatorial',
        name: 'Equatorial (Energia)',
        description: '2ª via do boleto de energia elétrica',
        url: 'https://agencia.equatorialenergia.com.br',
      },
      {
        id: 'titulo-eleitor',
        name: 'Título de Eleitor',
        description: '2ª via do título de eleitor',
        url: 'https://www.tse.jus.br/servicos-eleitorais/titulo-e-local-de-votacao/titulo-de-eleitor',
      },
    ],
  },
  {
    id: 'educacao',
    title: 'Educação',
    description: 'Acesso a programas, exames, faculdades e livros.',
    color: '#2E7D32',
    lightColor: '#E8F5E9',
    icon: 'graduation-cap',
    services: [
      {
        id: 'fies',
        name: 'FIES',
        description: 'Fundo de Financiamento Estudantil',
        url: 'https://acessounico.mec.gov.br/fies',
      },
      {
        id: 'enem',
        name: 'MEC (INEP) – ENEM',
        description: 'Informações e inscrições no ENEM',
        url: 'https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enem',
      },
      {
        id: 'sisu',
        name: 'SISU',
        description: 'Sistema de Seleção Unificada',
        url: 'https://sisu.mec.gov.br',
      },
      {
        id: 'prouni',
        name: 'PROUNI',
        description: 'Programa Universidade para Todos',
        url: 'https://acessounico.mec.gov.br/prouni',
      },
      {
        id: 'mec-livros',
        name: 'MEC Livros',
        description: 'Biblioteca Digital gratuita',
        url: 'https://plataformaintegrada.mec.gov.br',
      },
      {
        id: 'faculdade-vale-aco',
        name: 'Faculdade Vale do Aço',
        description: 'Portal do aluno e AVA',
        url: 'https://www.undb.edu.br',
      },
    ],
  },
  {
    id: 'financas',
    title: 'Finanças',
    description: 'Acesso rápido a bancos e serviços financeiros.',
    color: '#E65100',
    lightColor: '#FFF3E0',
    icon: 'landmark',
    services: [
      {
        id: 'banco-brasil',
        name: 'Banco do Brasil',
        description: 'Acesse sua conta no Banco do Brasil',
        url: 'https://www.bb.com.br',
      },
      {
        id: 'bradesco',
        name: 'Bradesco',
        description: 'Acesse sua conta no Bradesco',
        url: 'https://banco.bradesco',
      },
      {
        id: 'itau',
        name: 'Itaú',
        description: 'Acesse sua conta no Itaú',
        url: 'https://www.itau.com.br',
      },
      {
        id: 'santander',
        name: 'Santander',
        description: 'Acesse sua conta no Santander',
        url: 'https://www.santander.com.br',
      },
      {
        id: 'caixa',
        name: 'Caixa Econômica Federal',
        description: 'FGTS, Bolsa Família e muito mais',
        url: 'https://www.caixa.gov.br',
      },
      {
        id: 'nubank',
        name: 'Nubank',
        description: 'Acesse sua conta no Nubank',
        url: 'https://nubank.com.br',
      },
    ],
  },
  {
    id: 'documentacao',
    title: 'Documentação',
    description: 'Detran, TSE e antecedentes criminais.',
    color: '#6A1B9A',
    lightColor: '#F3E5F5',
    icon: 'id-card',
    services: [
      {
        id: 'detran',
        name: 'Detran (MA)',
        description: 'Serviços de trânsito do Maranhão',
        url: 'https://www.detran.ma.gov.br',
      },
      {
        id: 'tse',
        name: 'Tribunal Superior Eleitoral (TSE)',
        description: 'Título de eleitor e serviços eleitorais',
        url: 'https://www.tse.jus.br',
      },
      {
        id: 'antecedentes',
        name: 'Antecedentes Criminais',
        description: 'Emissão de certidão de antecedentes',
        url: 'https://www.gov.br/pf/pt-br/assuntos/antecedentes-criminais',
      },
      {
        id: 'seati',
        name: 'Agendamento RG / CIN e Procon',
        description: 'Agendamentos de atendimento presencial',
        url: 'https://www.seati.ma.gov.br',
      },
    ],
  },
  {
    id: 'agendamentos',
    title: 'Agendamentos',
    description: 'Agendamentos e serviços públicos importantes.',
    color: '#004D40',
    lightColor: '#E0F2F1',
    icon: 'calendar-check',
    services: [
      {
        id: 'agendamento-rg',
        name: 'Agendamento RG / CIN',
        description: 'Emissão da identidade — agende seu horário',
        url: 'https://www.seati.ma.gov.br',
      },
      {
        id: 'procon',
        name: 'Procon',
        description: 'Agendamento de atendimento ao consumidor',
        url: 'https://www.procon.ma.gov.br',
      },
      {
        id: 'outros-agendamentos',
        name: 'Outros Agendamentos',
        description: 'Serviços e atendimentos governamentais',
        url: 'https://www.gov.br/pt-br/servicos',
      },
    ],
  },
  {
    id: 'denuncias',
    title: 'Denúncias e Ocorrências',
    description: 'Registro de denúncias e ocorrências online.',
    color: '#C62828',
    lightColor: '#FFEBEE',
    icon: 'shield-alert',
    services: [
      {
        id: 'delegacia-virtual',
        name: 'Delegacia Virtual',
        description: 'Registre ocorrências online sem sair de casa',
        url: 'https://www.delegaciavirtual.ssp.ma.gov.br',
      },
      {
        id: 'disque-denuncia',
        name: 'Disque Denúncia (181)',
        description: 'Canal de denúncias anônimas do Maranhão',
        url: 'https://www.ssp.ma.gov.br',
      },
      {
        id: 'ligue-180',
        name: 'Ligue 180 – Violência contra a mulher',
        description: 'Central de atendimento à mulher em situação de violência',
        url: 'https://www.gov.br/mdh/pt-br/navegue-por-temas/politicas-para-mulheres/ligue-180',
      },
    ],
  },
  {
    id: 'saude',
    title: 'Saúde',
    description: 'Vacinas, exames e informações de saúde.',
    color: '#0D47A1',
    lightColor: '#E3F2FD',
    icon: 'heart-pulse',
    services: [
      {
        id: 'sus-digital',
        name: 'Meu SUS Digital',
        description: 'Carteira de vacinação, exames e cartão SUS',
        url: 'https://meususdigital.saude.gov.br',
      },
      {
        id: 'cnes',
        name: 'Unidades de Saúde (CNES)',
        description: 'Encontre postos e hospitais próximos a você',
        url: 'http://cnes.datasus.gov.br',
      },
      {
        id: 'samu',
        name: 'SAMU 192',
        description: 'Informações sobre o Serviço de Atendimento Móvel',
        url: 'https://www.gov.br/saude/pt-br/assuntos/samu',
      },
      {
        id: 'conecte-sus',
        name: 'Conecte SUS',
        description: 'Histórico de saúde e resultados de exames',
        url: 'https://conectesus.saude.gov.br',
      },
    ],
  },
  {
    id: 'emprego',
    title: 'Emprego',
    description: 'Carteira de trabalho, INSS e oportunidades.',
    color: '#E65100',
    lightColor: '#FFF8E1',
    icon: 'briefcase',
    services: [
      {
        id: 'ctps',
        name: 'Carteira de Trabalho Digital',
        description: 'Acesse sua CTPS e veja vínculos empregatícios',
        url: 'https://empregabrasil.mte.gov.br',
      },
      {
        id: 'inss',
        name: 'Meu INSS',
        description: 'Aposentadoria, benefícios e extratos',
        url: 'https://meu.inss.gov.br',
      },
      {
        id: 'seguro-desemprego',
        name: 'Seguro Desemprego',
        description: 'Solicite e acompanhe o seguro desemprego',
        url: 'https://sd.mte.gov.br',
      },
      {
        id: 'sine',
        name: 'SINE – Vagas de Emprego',
        description: 'Encontre vagas de emprego na sua região',
        url: 'https://www.gov.br/trabalho-e-emprego/pt-br/servicos/trabalhador/consulta-de-vagas-de-emprego',
      },
    ],
  },
  {
    id: 'servicos-uteis',
    title: 'Serviços úteis',
    description: 'Outros serviços e informações importantes.',
    color: '#006064',
    lightColor: '#E0F7FA',
    icon: 'layout-grid',
    services: [
      {
        id: 'correios',
        name: 'Correios',
        description: 'Rastreamento de encomendas e consulta de CEP',
        url: 'https://www.correios.com.br',
      },
      {
        id: 'gov-br',
        name: 'Portal Gov.br',
        description: 'Acesso a todos os serviços do governo federal',
        url: 'https://www.gov.br',
      },
      {
        id: 'ma-gov',
        name: 'Portal do Governo do MA',
        description: 'Serviços do estado do Maranhão',
        url: 'https://www.ma.gov.br',
      },
      {
        id: 'nota-fiscal',
        name: 'Nota Fiscal MA',
        description: 'Consulte e solicite notas fiscais de serviços',
        url: 'https://www.nfse.ma.gov.br',
      },
      {
        id: 'serpro',
        name: 'ReceitaNet (CPF)',
        description: 'Consulta e regularização de CPF',
        url: 'https://servicos.receita.fazenda.gov.br/servicos/cpf/consultasituacao/consultapublicaexb.asp',
      },
    ],
  },
];
